# Generated by Django 5.2.3 on 2025-07-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariapp', '0002_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad_disponible', models.CharField(max_length=100)),
                ('fecha_hora_vencimiento', models.DateTimeField()),
            ],
        ),
    ]
