# Generated by Django 5.2.3 on 2025-07-02 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariapp', '0003_medicamento_veterinario_bitacoraconsulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Programada', 'Programada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Programada', max_length=50)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='veterinariapp.mascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='veterinariapp.veterinario')),
            ],
        ),
    ]
